// =============================================================================
// THE INDEPENDENCE LAW FIRM — CLIENTS ROUTER
// src/routes/clients.ts
//
// Mounted at: /api/v1/clients  (see server.ts)
//
// Routes:
//   POST /api/v1/clients          — Register a new client (lawyer-only, Bearer token)
//   GET  /api/v1/clients/verify   — Verify email via magic-link token (public)
//   POST /api/v1/clients/login    — Client login → returns JWT (public)
//
// Authentication loop:
//   1. Lawyer POSTs to register a client → verification email dispatched
//   2. Client clicks link → GET /verify?token=<raw> → isVerified = true
//   3. Client POSTs login → password + isVerified checked → JWT returned
//
// Token security model:
//   - Registration: rawToken (UUID) generated; HMAC-SHA256 hash stored in DB.
//   - rawToken travels ONLY in the email URL — it is never stored.
//   - Verification: rawToken from URL is re-hashed and compared to DB value.
//   - This means a stolen DB backup cannot be used to verify accounts.
//
// NOTE ON TSC: PrismaClient types are generated by `prisma generate`. Run
// `npm run db:generate` after migration to enable full Prisma type checking.
// =============================================================================

import crypto from 'crypto';
import { Router, Request, Response, NextFunction } from 'express';
import bcrypt from 'bcrypt';
import jwt from 'jsonwebtoken';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '@prisma/client';

import { requireBearerToken } from '../middleware/auth';
import { sendVerificationEmail } from '../utils/email';

// ── Prisma client singleton (Prisma 7 — requires explicit pg adapter) ─────────
//
//   Prisma 7 does not auto-configure the database URL from the environment.
//   We must supply a pg Pool + PrismaPg adapter, matching prisma.config.ts.
//   The singleton is lazily initialised on first use and reused thereafter.
//
let _prisma: PrismaClient | null = null;

function getPrisma(): PrismaClient {
  if (!_prisma) {
    const pool    = new Pool({ connectionString: process.env.DATABASE_URL as string });
    const adapter = new PrismaPg(pool);
    _prisma = new PrismaClient({ adapter });
  }
  return _prisma;
}

const router = Router();

// =============================================================================
// POST /api/v1/clients
//
// Register a new client record. REQUIRES a valid invitation token from the
// "Velvet Rope" system — no open public registration.
//
// The caller must supply:
//   1. The API Bearer token (i.e., this is invoked by the lawyer-facing
//      Next.js admin, not the client directly).
//   2. An invitation `token` in the request body — this is validated against
//      the Invitation table before the account is created.
//
// Invitation validation:
//   - Token must exist in the Invitation table
//   - Token must not be expired (expiresAt > now)
//   - Token must not have been used before (isUsed === false)
//   - The email in the request body must match the invitation email
//   - On successful registration, the invitation is marked isUsed: true
//
// Request body (JSON):
//   {
//     name:     string  — Client full name                (required)
//     email:    string  — Client email address             (required, must match invite)
//     password: string  — Plain-text password              (required, min 8 chars)
//     lawyerId: string  — UUID of the assigning lawyer     (required)
//     token:    string  — Invitation token from invite link (required)
//   }
//
// Responses:
//   201  { id, name, email, lawyerId, createdAt }  — Client created, email sent
//   400  { error: string }                          — Validation failure
//   403  { error: string }                          — Invalid, expired, used, or
//                                                     email-mismatched invitation
//   409  { error: string }                          — Email already registered
//   500  { error: 'Internal server error' }         — Global handler
// =============================================================================

router.post(
  '/',
  requireBearerToken,
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const { name, email, password, lawyerId, token } = req.body as {
        name?: string;
        email?: string;
        password?: string;
        lawyerId?: string;
        token?: string;
      };

      // ── Field presence validation ──────────────────────────────────────────
      const missing: string[] = [];
      if (!name?.trim())     missing.push('name');
      if (!email?.trim())    missing.push('email');
      if (!password)         missing.push('password');
      if (!lawyerId?.trim()) missing.push('lawyerId');
      if (!token?.trim())    missing.push('token');

      if (missing.length > 0) {
        res.status(400).json({
          error: `Missing required fields: ${missing.join(', ')}`,
        });
        return;
      }

      // ── Email format validation ────────────────────────────────────────────
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email as string)) {
        res.status(400).json({ error: 'Invalid email address format' });
        return;
      }

      // ── Minimum password length ────────────────────────────────────────────
      if ((password as string).length < 8) {
        res.status(400).json({ error: 'Password must be at least 8 characters' });
        return;
      }

      // ════════════════════════════════════════════════════════════════════════
      // VELVET ROPE: Validate invitation token
      // ════════════════════════════════════════════════════════════════════════
      const prisma = getPrisma();
      const normalizedEmail = (email as string).trim().toLowerCase();

      const invitation = await prisma.invitation.findUnique({
        where: { token: (token as string).trim() },
      });

      // ── Token does not exist ───────────────────────────────────────────────
      if (!invitation) {
        res.status(403).json({ error: 'Invalid invitation token' });
        return;
      }

      // ── Token already used ─────────────────────────────────────────────────
      if (invitation.isUsed) {
        res.status(403).json({ error: 'This invitation has already been used' });
        return;
      }

      // ── Token expired ──────────────────────────────────────────────────────
      if (new Date() > new Date(invitation.expiresAt)) {
        res.status(403).json({ error: 'This invitation has expired' });
        return;
      }

      // ── Email mismatch ─────────────────────────────────────────────────────
      if (invitation.email !== normalizedEmail) {
        res.status(403).json({ error: 'Email address does not match the invitation' });
        return;
      }

      // ── Step 1: Hash password (bcrypt, cost 12) ────────────────────────────
      const passwordHash = await bcrypt.hash(password as string, 12);

      // ── Step 2: Generate verification token ───────────────────────────────
      //
      //   rawToken   → travels ONLY inside the email link URL
      //   storedHash → HMAC-SHA256(rawToken, JWT_SECRET) — stored in DB
      //
      //   On verification: re-hash the URL token and compare to storedHash.
      //   A stolen DB backup cannot be replayed to verify accounts.
      //
      const rawToken = crypto.randomBytes(32).toString('hex');
      const verificationToken = crypto
        .createHmac('sha256', process.env.JWT_SECRET as string)
        .update(rawToken)
        .digest('hex');
      const verificationExpires = new Date(Date.now() + 24 * 60 * 60 * 1000); // +24h

      // ── Step 3: Persist via Prisma ─────────────────────────────────────────
      const client = await prisma.client.create({
        data: {
          name:               (name as string).trim(),
          email:              normalizedEmail,
          passwordHash,
          lawyerId:           (lawyerId as string).trim(),
          verificationToken,
          verificationExpires,
        },
        // Return only safe, non-sensitive fields
        select: {
          id:        true,
          name:      true,
          email:     true,
          lawyerId:  true,
          createdAt: true,
        },
      });

      // ── Step 4: Mark invitation as used ────────────────────────────────────
      await prisma.invitation.update({
        where: { id: invitation.id },
        data:  { isUsed: true },
      });

      // ── Step 5: Send verification email ───────────────────────────────────
      //
      //   We pass rawToken (not the hash) — the email utility embeds it in
      //   the magic-link URL for the client to click.
      //   Fire-and-forget pattern: email failure is logged but does NOT roll
      //   back the record — the lawyer can trigger a resend later.
      //
      try {
        await sendVerificationEmail(client.email, rawToken);
      } catch (emailErr) {
        console.error('[clients] Verification email failed (client created):', emailErr);
        // Continue — return 201, surface email failure via server logs
      }

      // ── Step 6: Return created client (safe fields only) ──────────────────
      res.status(201).json(client);

    } catch (err) {
      // ── Prisma unique-constraint violation (duplicate email) ───────────────
      if (
        err !== null &&
        typeof err === 'object' &&
        'code' in err &&
        (err as { code: string }).code === 'P2002'
      ) {
        res.status(409).json({ error: 'Email address is already registered' });
        return;
      }

      next(err);
    }
  }
);


// =============================================================================
// GET /api/v1/clients/verify
//
// Verifies a client's email address using the raw token from the magic link.
// This route is PUBLIC — no Bearer token required (the client clicks the link).
//
// Query parameters:
//   token  string  — The raw hex token embedded in the email link  (required)
//
// Responses:
//   200  { message: string }  — Email verified, client may now log in
//   400  { error: string }    — Token missing, invalid, or expired
//   500  { error: string }    — Global handler
// =============================================================================

router.get(
  '/verify',
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const { token } = req.query as { token?: string };

      // ── Token presence check ───────────────────────────────────────────────
      if (!token || typeof token !== 'string' || !token.trim()) {
        res.status(400).json({ error: 'Verification token is required' });
        return;
      }

      // ── Re-hash the raw token to match what is stored in the DB ───────────
      const hashedToken = crypto
        .createHmac('sha256', process.env.JWT_SECRET as string)
        .update(token.trim())
        .digest('hex');

      // ── Look up client by hashed token ────────────────────────────────────
      const prisma = getPrisma();
      const client = await prisma.client.findFirst({
        where: { verificationToken: hashedToken },
        select: {
          id:                  true,
          isVerified:          true,
          verificationExpires: true,
        },
      });

      // ── Token not found ────────────────────────────────────────────────────
      if (!client) {
        res.status(400).json({ error: 'Invalid or expired verification link' });
        return;
      }

      // ── Already verified ───────────────────────────────────────────────────
      if (client.isVerified) {
        res.status(200).json({ message: 'Email address already verified. You may log in.' });
        return;
      }

      // ── Expiry check ───────────────────────────────────────────────────────
      if (!client.verificationExpires || new Date() > new Date(client.verificationExpires)) {
        res.status(400).json({ error: 'Verification link has expired. Please contact your lawyer to resend.' });
        return;
      }

      // ── Mark as verified, clear token fields ───────────────────────────────
      await prisma.client.update({
        where: { id: client.id },
        data: {
          isVerified:          true,
          verificationToken:   null,
          verificationExpires: null,
        },
      });

      res.status(200).json({
        message: 'Email address verified successfully. You may now log in to the Independence Law Client Portal.',
      });

    } catch (err) {
      next(err);
    }
  }
);

// =============================================================================
// POST /api/v1/clients/login
//
// Authenticates a verified client and issues a signed JWT.
// This route is PUBLIC — no Bearer token required (the client logs in directly).
//
// Request body (JSON):
//   {
//     email:    string  — Client email address  (required)
//     password: string  — Client password       (required)
//   }
//
// Responses:
//   200  { token: string, client: { id, name, email, lawyerId } }
//         — Authentication successful; JWT valid for JWT_EXPIRES_IN (default 7d)
//   400  { error: string }   — Missing fields
//   401  { error: string }   — Invalid email or password (intentionally vague)
//   403  { error: string }   — Account exists but email not yet verified
//   500  { error: string }   — Global handler
// =============================================================================

router.post(
  '/login',
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const { email, password } = req.body as {
        email?: string;
        password?: string;
      };

      // ── Field presence validation ──────────────────────────────────────────
      if (!email?.trim() || !password) {
        res.status(400).json({ error: 'Email and password are required' });
        return;
      }

      // ── Look up client by email ────────────────────────────────────────────
      const prisma = await getPrisma();
      const client = await prisma.client.findUnique({
        where: { email: (email as string).trim().toLowerCase() },
        select: {
          id:           true,
          name:         true,
          email:        true,
          lawyerId:     true,
          passwordHash: true,
          isVerified:   true,
        },
      });

      // ── Client not found — return generic 401 (no enumeration signal) ──────
      if (!client) {
        res.status(401).json({ error: 'Invalid email or password' });
        return;
      }

      // ── Password check ─────────────────────────────────────────────────────
      const passwordMatch = await bcrypt.compare(password as string, client.passwordHash);
      if (!passwordMatch) {
        res.status(401).json({ error: 'Invalid email or password' });
        return;
      }

      // ── Verification gate: must verify email before logging in ────────────
      if (!client.isVerified) {
        res.status(403).json({
          error: 'Please verify your email address before logging in. Check your inbox for the verification link.',
        });
        return;
      }

      // ── Issue JWT ──────────────────────────────────────────────────────────
      //
      //   Payload: { sub: clientId }  — minimal surface area.
      //   The frontend should decode the token to get the ID, then call
      //   the API for any additional profile data (don't trust JWT payload
      //   for sensitive decisions — always re-validate server-side).
      //
      const jwtSecret  = process.env.JWT_SECRET as string;
      const expiresIn  = (process.env.JWT_EXPIRES_IN ?? '7d') as jwt.SignOptions['expiresIn'];

      const token = jwt.sign(
        { sub: client.id },
        jwtSecret,
        { expiresIn },
      );

      // ── Return token + safe client profile ────────────────────────────────
      res.status(200).json({
        token,
        client: {
          id:       client.id,
          name:     client.name,
          email:    client.email,
          lawyerId: client.lawyerId,
        },
      });

    } catch (err) {
      next(err);
    }
  }
);

export default router;
