// =============================================================================
// THE INDEPENDENCE LAW FIRM — CLIENTS ROUTER
// src/routes/clients.ts
//
// Mounted at: /api/v1/clients  (see server.ts)
//
// Routes:
//   POST /api/v1/clients   — Register a new client record
//                            (guarded by requireBearerToken)
//
// Registration flow:
//   1. Validate all required fields and email format
//   2. Hash password with bcrypt (cost 12)
//   3. Generate HMAC-SHA256 verification token (raw UUID travels email-only)
//   4. Persist via Prisma; catch P2002 (duplicate email) → 409
//   5. Return 201 with safe fields only (no passwordHash in response)
//
// NOTE: Email delivery (Step 6) will be wired in v1.3 — SES/Resend milestone.
//
// NOTE ON TSC: PrismaClient types are generated by `prisma generate` which runs
// automatically after `prisma migrate dev`. Until then, the import resolves at
// runtime only. Run `npm run db:generate` after migration to enable full type
// checking of Prisma models.
// =============================================================================

import crypto from 'crypto';
import { Router, Request, Response, NextFunction } from 'express';
import bcrypt from 'bcrypt';

import { requireBearerToken } from '../middleware/auth';

// ── Lazy Prisma client ────────────────────────────────────────────────────────
//
//   We import PrismaClient lazily so that the module loads cleanly even before
//   `prisma generate` has run. Once the migration completes, replace this block
//   with a standard top-level singleton import from '@prisma/client'.
//
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let _prisma: any = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function getPrisma(): Promise<any> {
  if (!_prisma) {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const { PrismaClient } = require('@prisma/client');
    _prisma = new PrismaClient();
  }
  return _prisma;
}

const router = Router();

// ── POST /api/v1/clients ──────────────────────────────────────────────────────
//
//   Creates a new client record in the database.
//
//   Request body (JSON):
//     {
//       name:     string  — Client full name                 (required)
//       email:    string  — Client email address              (required, unique)
//       password: string  — Plain-text password               (required, min 8 chars)
//       lawyerId: string  — UUID of the assigning lawyer      (required)
//     }
//
//   Responses:
//     201  { id, name, email, lawyerId, createdAt }  — Client created
//     400  { error: string }                          — Validation failure
//     409  { error: string }                          — Email already registered
//     500  { error: 'Internal server error' }         — Caught by global handler
//
router.post(
  '/',
  requireBearerToken,
  async (req: Request, res: Response, next: NextFunction): Promise<void> => {
    try {
      const { name, email, password, lawyerId } = req.body as {
        name?: string;
        email?: string;
        password?: string;
        lawyerId?: string;
      };

      // ── Field presence validation ──────────────────────────────────────────
      const missing: string[] = [];
      if (!name?.trim())     missing.push('name');
      if (!email?.trim())    missing.push('email');
      if (!password)         missing.push('password');
      if (!lawyerId?.trim()) missing.push('lawyerId');

      if (missing.length > 0) {
        res.status(400).json({
          error: `Missing required fields: ${missing.join(', ')}`,
        });
        return;
      }

      // ── Email format validation ────────────────────────────────────────────
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(email as string)) {
        res.status(400).json({ error: 'Invalid email address format' });
        return;
      }

      // ── Minimum password length ────────────────────────────────────────────
      if ((password as string).length < 8) {
        res.status(400).json({ error: 'Password must be at least 8 characters' });
        return;
      }

      // ── Step 1: Hash password (bcrypt, cost 12) ────────────────────────────
      const passwordHash = await bcrypt.hash(password as string, 12);

      // ── Step 2: Generate verification token ───────────────────────────────
      //
      //   The raw UUID travels ONLY inside the email link — never stored.
      //   We store only its HMAC-SHA256 hash. On verification, the raw
      //   token from the URL is re-hashed and compared to the stored value.
      //
      const rawToken = crypto.randomUUID();
      const verificationToken = crypto
        .createHmac('sha256', process.env.JWT_SECRET as string)
        .update(rawToken)
        .digest('hex');
      const verificationExpires = new Date(Date.now() + 24 * 60 * 60 * 1000); // +24h

      // ── Step 3: Persist via Prisma ─────────────────────────────────────────
      const prisma = await getPrisma();
      const client = await prisma.client.create({
        data: {
          name:               (name as string).trim(),
          email:              (email as string).trim().toLowerCase(),
          passwordHash,
          lawyerId:           (lawyerId as string).trim(),
          verificationToken,
          verificationExpires,
        },
        // Return only safe, non-sensitive fields
        select: {
          id:        true,
          name:      true,
          email:     true,
          lawyerId:  true,
          createdAt: true,
        },
      });

      // ── Step 4: TODO — Send verification email ─────────────────────────────
      //   await sendVerificationEmail({ to: client.email, rawToken });
      //   (Wired in v1.3 — SES / Resend integration milestone)

      // ── Step 5: Return created client (safe fields only) ──────────────────
      res.status(201).json(client);

    } catch (err) {
      // ── Prisma unique-constraint violation (duplicate email) ───────────────
      //
      //   Prisma error code P2002 = "Unique constraint failed on email column".
      //   We map this to a clean 409 Conflict — no DB internals leak to client.
      //
      if (
        err !== null &&
        typeof err === 'object' &&
        'code' in err &&
        (err as { code: string }).code === 'P2002'
      ) {
        res.status(409).json({ error: 'Email address is already registered' });
        return;
      }

      // ── All other errors → global error handler in server.ts ──────────────
      next(err);
    }
  }
);

export default router;
